spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: TestTest1234
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.MySQL8Dialect